### ISSUE TITLE
Ability to switch QJS forks?

### ISSUE THREAD

**Issue by stevefan1999-personal** [DelSkayn/rquickjs#126]
You know, the main code from Bellard wasn't updated for a long time, so I think we should investigate other forks such as this one: [suchipi/quickjs: Standalone or embeddable C99 JavaScript Engine (github.com)](https://github.com/suchipi/quickjs). 

I found it by looking up the GH dependency graph and chose the most active fork which I think is great, despite it was using Ninja and far as I know there is no Ninja build support for Rust build script yet.

**Comment by Sytten** [comment]
Maybe pulling the 2022 changes would be a first step

**Comment by DelSkayn** [comment]
I am going to close this because we are not going to be able to support switching QJS forks. 

Different forks might have subtle differences in implementation which can break rquickjs. There isn't good documentation for what is and isn't public interface with QuickJS so forks might break stuff which rquickjs relies on. Furthermore rquickjs requires patches which assumes a certain specific code base to function.

Were switching to QuickJS-NG which I think is the most up-to-date fork and aught to be good enough for most people.
