### ISSUE TITLE
Compilation error in ARM

### ISSUE THREAD

**Issue by Martin1887** [DelSkayn/rquickjs#169]
The compilation of `rquickjss-sys-0.3.0` fails in ARM aarch64 (in Pinebook Pro) with the following error:

![image](https://github.com/DelSkayn/rquickjs/assets/4211771/74bf4b82-d1d4-4881-a96b-fcc486d69cef)

Thanks.

**Comment by DelSkayn** [comment]
I think I fixed the problem, bindgen recently switched to using `usize` for C `size_t` type. But I found this to have lead to some problems where certain platforms `size_t` is a `u64` instead of `usize`. So I changed the library to use `size_t` again. 

Just to verify, what platform triple (for example `aarch64-unknown-linux-gnu`) is the Pinebook Pro?

**Comment by Martin1887** [comment]
It's exactly àarch64-unknown-linux-gnu`. Thanks!

**Comment by Martin1887** [comment]
I have just tried it using the `main` git path as dependency and it works, so the issue can be closed.

However, a new release would avoid having to point to the `main` branch.


Thanks!

**Comment by DelSkayn** [comment]
I have just released a new version with the fix. 0.3.1 should no longer contain the bug.

**Comment by Martin1887** [comment]
Thanks!
