### ISSUE TITLE
type_of() returns Constructor for all non-arrow functions.

### ISSUE THREAD

**Issue by richarddd** [DelSkayn/rquickjs#192]
When passing a named or anon function they are treated like `Constructors` and behave different from JS.

```javascript
const reference = function(){
}

function namedFunction(){
}

print(typeof reference)
print(typeof namedFunction)
printTypeofRust(reference)
printTypeofRust(namedFunction)
printTypeofRust(() => {})
```

```rust
globals.set("print", Func::from(|value:String| {
    println!("{}", value);
}))?;
globals.set("printTypeofRust", Func::from(|value: Value| {
    let type_of = value.type_of();
    println!("{:?}", type_of);
}))?;
```

Output:

```
function
function
Constructor
Constructor
Function
```

**Comment by DelSkayn** [comment]
This is the intended behavior, all those functions are constructors as they can be used as constructors. Constructor is a sub type of Function.

I didn't really intend to have the type_of function to be the same as the JavaScript typeof operator. The type has a bunch more variants then what the typeof operator can return, like Float, Int, Array, Exception and Constructor. Especially Float and Int are a integral part of rquickjs since QuickJS values store JavaScript numbers in either a Float or an Int.
