### ISSUE TITLE
Await in javascript throws error

### ISSUE THREAD

**Issue by azam** [DelSkayn/rquickjs#235]
This code throws an Err with message "Exception generated by quickjs".
Is this code wrong, or is there a limitation of some sort?
Tested on `rquickjs = { version = "0.3.1", features = ["full-async"] }` with `async-std` and `tokio`

```rust
let rt = AsyncRuntime::new().unwrap();
let ctx = AsyncContext::full(&rt).await.unwrap();
async_with!(ctx => |ctx| {
    // Expecting Ok(69)
    let val = ctx.eval::<u64, _>("await (async () => 69)()"); // or just `await 69`
    match val {
        Ok(v) => eprintln!("Ok: {}", v),
        Err(v) => eprintln!("Err: {}", v), // Err: Exception generated by quickjs
    };
})
.await;
```

**Comment by DelSkayn** [comment]
QuickJS doesn't support top level await, so it generates an error for `await (async() => 69)`. 

This error isn't displayed because of some design choices we had to make in the library.
If you want to see what the specific error is that is raise you need to first retrieve it from the context.
If you use [`CatchResultExt::catch`](https://docs.rs/rquickjs/latest/rquickjs/trait.CatchResultExt.html#tymethod.catch) you can retrieve the error from the context and you will see that QuickJS returns an error.

**Comment by azam** [comment]
Got it. Thank you for the explanation!
For others that may encounter this, my error was: `Exception generated by quickjs:  'await' is not defined`

**Comment by zamfofex** [comment]
Hello, I arrived at this repository from [LLRT]!

[LLRT]: <https://github.com/awslabs/llrt>

In case you want to add support for top level `await`, I wanted to say that I have made [a patch that I submitted to the QuickJS mailing list about a year ago][lists].

[lists]: <https://www.freelists.org/post/quickjs-devel/PATCH-toplevel-await-TLA>

The patch [was eventually added to txiki.js][txiki], and I’ve also just [uploaded my original patch to sr.ht][patch].

[txiki]: <https://github.com/saghul/txiki.js/pull/362>
[patch]: <https://paste.sr.ht/~zamfofex/f37129ef21c8bfbee8c864a89b343d1b54d22c6a>

<details><summary>notes on the future of QuickJS</summary>

Also, QuickJS seems to be mostly abandoned by its main developers currently, but there seems to be efforts to revive the project by the developer(s) of txiki.js, called [“QuickJS‐ng”][QuickJS-ng]. Maybe it would make sense to keep future work on QuickJS in a single repository, to avoid accidental duplication of efforts. (And I think it would be better to choose an option that seems to be willing to accept changes and updates, rather than upstream QuickJS.)

[QuickJS-ng]: <https://github.com/quickjs-ng/quickjs>

</details>
