### ISSUE TITLE
Can't build with both `bindgen` and `macro` features enabled

### ISSUE THREAD

**Issue by ryangjchandler** [DelSkayn/rquickjs#36]
Using the `bindgen` feature since I'm on an M1 MacBook and there's no binary provided. If I remove the `macro` feature, it works fine.

**Comment by katyo** [comment]
Such behavior is expected because the `embed` macro requires binding to JS engine on a host to be able to compile JS to bytecode.
As one of possible solution we may add feature to enable/disable `embed` macro separately.
Or we may simply disable bytecode compilation support via feature (or by default).
In short words this is not a bug.

Could you create PR with generated bindings for M1?

**Comment by ryangjchandler** [comment]
@katyo Thanks for the reply. Are there any instructions for PR'ing the generated bindings?

**Comment by katyo** [comment]
@ryangjchandler 
You can simply build `sys` crate with `update-bindings` feature like the following:
```sh
cd sys
cargo build --features exports,bindgen,update-bindings
```

Generated binding will be copied to `sys/src/bindings/aarch64-apple-darwin.rs` (or something like so).
Add and create commit with this file.

**Comment by ryangjchandler** [comment]
Awesome, I'll open a PR now!

**Comment by ryangjchandler** [comment]
@katyo PR at #37.
