### ISSUE TITLE
How do I implement Trace for foreign object?

### ISSUE THREAD

**Issue by stevefan1999-personal** [DelSkayn/rquickjs#402]
For example I want to trace the memory for my wasmtime instance to prevent leaks:
```rust
#[derive(Trace, JsLifetime, Clone, Deref, DerefMut, From, Into)]
#[rquickjs::class]
pub struct Memory<'js> {
    pub(crate) inner: wasmtime::Memory,

    #[deref(ignore)]
    #[deref_mut(ignore)]
    pub(crate) store: crate::store::Store<'js>,
}
```
But it seems like I can't. Although I can "skip trace", it is certainly dangerous to do so. So how do I actually do it to prevent the wasmtime objects still holding a reference to the Ctx of QuickJS?

**Comment by DelSkayn** [comment]
Due to rust orphan rule if you want to implement it for a foreign type you will have to implement it for a wrapper type. However skip trace is probably fine in this case. Only types which can contain rquickjs object and values need to implement trace so for most foreign types you won't need to implement it as they cannot contain rquickjs types.

**Comment by stevefan1999-personal** [comment]
I see. I have tried to use the new user data feature instead to work around the wasmtime store issue. This would make web worker implementation a little bit complicated but it will work for now.
