### ISSUE TITLE
Cannot use `bind` or `apply` or other `Function.prototype` methods on a native function

### ISSUE THREAD

**Issue by jeromegn** [DelSkayn/rquickjs#59]
For example:

```rust
fn print(msg: String) {
    println!("{}", msg);
}

fn main() {
    let mut rt = Runtime::new().unwrap();
    let mut ctx = Context::full(&rt).unwrap();

    ctx.with(|ctx| {
        ctx.globals().set("print", Func::new("print", print)).unwrap();
        ctx.eval::<(), _>(r#"print.bind(this, "hello")();"#).unwrap();
    })
}
```

Results in this error:

```
Exception { message: "not a function", file: "", line: -1, stack: "    at <eval> (eval_script:2)\n" }
```

**Comment by DelSkayn** [comment]
This is somewhat by design. In quickjs C functions (or rust functions) have their prototype set to the object prototype. There is no real good way to set the prototype of function objects to the function prototype from which the `bind` and `apply` functions are derived. 

The best way to solve this issue is to wrap C/rust functions on the javascript side with a javascript function.

**Comment by katyo** [comment]
@DelSkayn We can try to use Function.prototype as prototype for Rust functions but I'm not sure.

**Comment by DelSkayn** [comment]
> @DelSkayn We can try to use Function.prototype as prototype for prototype of Rust functions but I'm not sure.

I have looked into setting the prototype of native functions to Function.prototype. The problem I encountered is that there is no good way to access the function prototype object from rust as quickjs does not allow you to access it. Which might mean that that prototype is only meant for javascript functions and not for C functions but I am not sure about that.

As I see it right now there are three options:
1. Patching quickjs so that we can access prototype object.
2. Doing something like `let func_proto = ctx.eval("Function.prototype")` at library initialization and than use the returned object as a prototype for functions.
3. When creating a native function wrapping it with `(...args) => nativeFunc(...args)` in javascript.

Option 1 and 2 felt too much like a hack to me and option 3 seems like it could cause some overhead as I did not like the requirement to have to run `Ctx.eval` for every function created. 
So it seemed to me that the best solution was to have users just wrap functions if they need defined prototype methods as with something like:
```rust
fn wrap_func<'js>(ctx: Ctx<'js>, func: Function<'js>) -> rquickjs::Result<Function<'js>> {
    ctx.eval::<Function, _>("(f) => (...args) => f(...args)")?
        .call((func,))?
}
```
