### ISSUE TITLE
Panic when using BigInt

### ISSUE THREAD

**Issue by tobiemh** [DelSkayn/rquickjs#74]
Hi,

I am receiving the following panic when attempting to use BigInt from within rquickjs.

I am setting up the `Context` with:

```rust
let run = Runtime::new().unwrap();
let ctx = Context::full(&run).unwrap();
ctx.enable_big_num_ext(true);
ctx.with(|ctx| {
    ctx.eval(src)
})
```

With the `src` as 
```js
(async function() {
    return BigInt("9007199254740991");
})()
```

I receive the following panic:

```bash
thread 'tokio-runtime-worker' panicked at 'Unknown JS value tag: -10', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-core-0.1.6/src/value.rs:438:1
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-core-0.1.6/src/safe_ref.rs:40:27
```

**Comment by DelSkayn** [comment]
Hi! Thank you for creating this issue!

Rquickjs does not yet support handling bigints and thus panics because it thinks the object it received from the quickjs library is invalid. 

here is a shorter snippet which results in a panic:
```rust
use rquickjs::{Context, Runtime};

fn main() {
    let run = Runtime::new().unwrap();
    let ctx = Context::full(&run).unwrap();
    ctx.enable_big_num_ext(true);

    let _: i32 = ctx.with(|ctx| ctx.eval("0n").unwrap());
}
```

Proper bigint support would probably also need a support on the rust end of things and should probably be behind feature. In the mean time the library should probably not panic if it happened to receive a valid object it does not know what to do with. 

I think handling this with an error when converting instead.

**Comment by DelSkayn** [comment]
I am closing this for now. Rquickjs now has a value for representing BigInt's and no longer panics.
Support is still somewhat limited, mostly due to quickjs API being very limited in what can be done with BigInt's. 

I will create an issue for adding more support for bigint's in the future.
